### ISSUE TITLE
Missing licenses in vendor directory

### ISSUE THREAD

**Issue by glaslos** [trivago/gollum#64] opened 2017-01-19 14:07 UTC
The package source code in the vendor directory is missing the license information. This might be related to https://github.com/FiloSottile/gvt/issues/46 or https://github.com/FiloSottile/gvt/issues/23
This is probably violating most of the licenses used by packages in the vendor directory.

**Comment by arnecls** [comment] 2017-01-19 14:08
Thanks for noticing ... let's see how we can fix that quickly ... 🤔

**Comment by glaslos** [comment] 2017-01-19 14:29
Actually it might be the `.gitignore`, adding `!LICENSE` (+all the other variants) could be the solution.

**Comment by arnecls** [comment] 2017-01-19 14:31
Interestingly https://github.com/trivago/gollum/tree/master/vendor/github.com/eapache/queue contains a license file

**Comment by arnecls** [comment] 2017-01-19 14:32
I've forwarded this to legal because I am not 100% sure about the situation here.
If the source of the problem is GVT we might need to switch the vendor tool, because I don't want to adde license files manually each time a new dependency arrives ...

**Comment by arnecls** [comment] 2017-02-17 08:53
License files should be included for all vendors on the 0.4.5dev branch.

**Comment by arnecls** [comment] 2017-02-20 15:56
A little update on this issue (details are still being evaluated).
1. We will add all missing license files for the next release (0.4.5)
2. If _requested_ we will also fix this for already released versions*
3. You can always restore the license files by using `gvt restore`

*because licenses can be restored easily and fixing old releases is quite a bit of work.

**Comment by arnecls** [comment] 2017-04-03 13:25
0.4.5 has been merged, missing license files have been added.
I also did some clarifications with our legal department and (as of now) it should be sufficient to have the License files in the vendor folder.

**Closed** 2017-04-03 13:25 UTC
Labels: enhancement
